/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import helper.ChainCode;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JInternalFrame;

/**
 *
 * @author Zavyra
 */
public class ChainCodeView extends JInternalFrame {

    private ArrayList<ChainCode> codes;

    /**
     * Creates new form ChainCodeView
     */
    public ChainCodeView(ArrayList<ChainCode> codes) {
        initComponents();
        this.codes = codes;
        setList();
    }

    private void setList() {
        Vector<String> v = new Vector<>();
        for (int i = 0; i < codes.size(); i++) {
            v.add("#" + i);            
        }
        listChainCode.setListData(v);
    }
    
    private void setView(ChainCode cc) {
        textChainCode.setText(cc.getCodes());
        textShape.setText(cc.getShape());
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < 4; i++) {
            sb.append(i);
            sb.append(" : ");
            sb.append(cc.getFrequency()[i]);
            sb.append(" (");
            sb.append(cc.getFrequencyPercentage()[i]);
            sb.append("%)    ");
            sb.append(i+4);
            sb.append(" : ");
            sb.append(cc.getFrequency()[i+4]);
            sb.append(" (");
            sb.append(cc.getFrequencyPercentage()[i+4]);
            sb.append("%)\n");
        }
        textFrequency.setText(sb.toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listChainCode = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        textChainCode = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textFrequency = new javax.swing.JTextArea();
        textShape = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Chaincode :");

        jLabel2.setText("Frequency :");

        jLabel3.setText("Shape :");

        listChainCode.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listChainCodeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listChainCode);

        textChainCode.setColumns(20);
        textChainCode.setLineWrap(true);
        textChainCode.setRows(2);
        jScrollPane2.setViewportView(textChainCode);

        textFrequency.setColumns(20);
        textFrequency.setRows(4);
        jScrollPane3.setViewportView(textFrequency);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(textShape))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textShape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listChainCodeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listChainCodeValueChanged
        setView(codes.get(listChainCode.getSelectedIndex()));
    }//GEN-LAST:event_listChainCodeValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listChainCode;
    private javax.swing.JTextArea textChainCode;
    private javax.swing.JTextArea textFrequency;
    private javax.swing.JTextField textShape;
    // End of variables declaration//GEN-END:variables
}
